// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e59af84b-4f97-47b4-8ef0-ffab25a239e5',
    managementCertificate: {
      key: 'mockedKey',
      cert: 'mockedCert'
    },
    name: 'Windows Azure MSDN - Visual Studio Ultimate',
    registeredProviders: ['mobileservice'],
    registeredResourceNamespaces: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .post('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?targetMobileService=brettsam-east-test')
  .reply(200, "6e341a63f5f54d3c8fc4a0ed332ecde7", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '32',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '73b676cd644987d88b79b3e9dcfd5240',
  date: 'Mon, 06 Apr 2015 17:37:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .post('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?targetMobileService=brettsam-east-test')
  .reply(200, "6e341a63f5f54d3c8fc4a0ed332ecde7", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '32',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '73b676cd644987d88b79b3e9dcfd5240',
  date: 'Mon, 06 Apr 2015 17:37:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '9ef9700b4ee2888791044731dbd0c530',
  date: 'Mon, 06 Apr 2015 17:37:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '9ef9700b4ee2888791044731dbd0c530',
  date: 'Mon, 06 Apr 2015 17:37:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'aa59547697628ef1a04063d5b3d3c0d5',
  date: 'Mon, 06 Apr 2015 17:37:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'aa59547697628ef1a04063d5b3d3c0d5',
  date: 'Mon, 06 Apr 2015 17:37:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'df166987e1b481a1836122e441c205fb',
  date: 'Mon, 06 Apr 2015 17:37:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'df166987e1b481a1836122e441c205fb',
  date: 'Mon, 06 Apr 2015 17:37:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '3615f903618184afada987a3dd8198e7',
  date: 'Mon, 06 Apr 2015 17:37:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '3615f903618184afada987a3dd8198e7',
  date: 'Mon, 06 Apr 2015 17:37:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth2',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'd6c68702c030887e9ecc64b90ac3acc4',
  date: 'Mon, 06 Apr 2015 17:37:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth2',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'd6c68702c030887e9ecc64b90ac3acc4',
  date: 'Mon, 06 Apr 2015 17:37:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '81bb8bb50bea88e990d4e66b9960db5a',
  date: 'Mon, 06 Apr 2015 17:37:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '81bb8bb50bea88e990d4e66b9960db5a',
  date: 'Mon, 06 Apr 2015 17:37:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'cfe496d264d9885cab51e38abd1bfd40',
  date: 'Mon, 06 Apr 2015 17:37:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'cfe496d264d9885cab51e38abd1bfd40',
  date: 'Mon, 06 Apr 2015 17:37:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '150833bcfac6804d9b55010a656a1c44',
  date: 'Mon, 06 Apr 2015 17:37:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '150833bcfac6804d9b55010a656a1c44',
  date: 'Mon, 06 Apr 2015 17:37:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '4e989d846f6b8c8687cf9d11d7488e6b',
  date: 'Mon, 06 Apr 2015 17:37:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '4e989d846f6b8c8687cf9d11d7488e6b',
  date: 'Mon, 06 Apr 2015 17:37:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'b6076ac6a00d87e792f57d1eecb1d470',
  date: 'Mon, 06 Apr 2015 17:38:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'b6076ac6a00d87e792f57d1eecb1d470',
  date: 'Mon, 06 Apr 2015 17:38:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'dc2f34ce72c884fe8d76b12e0866c43b',
  date: 'Mon, 06 Apr 2015 17:38:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'dc2f34ce72c884fe8d76b12e0866c43b',
  date: 'Mon, 06 Apr 2015 17:38:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'b041ee46e9358daca101a144518b33b1',
  date: 'Mon, 06 Apr 2015 17:38:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'b041ee46e9358daca101a144518b33b1',
  date: 'Mon, 06 Apr 2015 17:38:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'f58fb02095e7827888e408697048d4da',
  date: 'Mon, 06 Apr 2015 17:38:21 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'f58fb02095e7827888e408697048d4da',
  date: 'Mon, 06 Apr 2015 17:38:21 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'f8ca3c1d0db580529f5512d6d4a7b534',
  date: 'Mon, 06 Apr 2015 17:38:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'f8ca3c1d0db580529f5512d6d4a7b534',
  date: 'Mon, 06 Apr 2015 17:38:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '50ce1e9b322c8705816dd5f2a6618087',
  date: 'Mon, 06 Apr 2015 17:38:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '50ce1e9b322c8705816dd5f2a6618087',
  date: 'Mon, 06 Apr 2015 17:38:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'f1e3e32984668ffc9591e550226acbbd',
  date: 'Mon, 06 Apr 2015 17:38:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'f1e3e32984668ffc9591e550226acbbd',
  date: 'Mon, 06 Apr 2015 17:38:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'cf307b29d2708be9bd61e3bf8d70cd77',
  date: 'Mon, 06 Apr 2015 17:38:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'cf307b29d2708be9bd61e3bf8d70cd77',
  date: 'Mon, 06 Apr 2015 17:38:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'a895413276538bc6b18d0fb332b24249',
  date: 'Mon, 06 Apr 2015 17:38:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'a895413276538bc6b18d0fb332b24249',
  date: 'Mon, 06 Apr 2015 17:38:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '1b435e827a9e8ee9aa69e8d896a08c39',
  date: 'Mon, 06 Apr 2015 17:38:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '1b435e827a9e8ee9aa69e8d896a08c39',
  date: 'Mon, 06 Apr 2015 17:38:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Completed", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '9',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'b9bb9b34342a831a9505dc37301e6175',
  date: 'Mon, 06 Apr 2015 17:39:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=6e341a63f5f54d3c8fc4a0ed332ecde7')
  .reply(200, "Completed", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '9',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'b9bb9b34342a831a9505dc37301e6175',
  date: 'Mon, 06 Apr 2015 17:39:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .delete('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/applications/brettsam-east-testmobileservice')
  .reply(202, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'x-ms-request-id': '9eaf7d7977d98631bffbfb3417641e65',
  date: 'Mon, 06 Apr 2015 17:39:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .delete('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/applications/brettsam-east-testmobileservice')
  .reply(202, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'x-ms-request-id': '9eaf7d7977d98631bffbfb3417641e65',
  date: 'Mon, 06 Apr 2015 17:39:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/operations/9eaf7d7977d98631bffbfb3417641e65')
  .reply(200, "<Operation xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><ID>9eaf7d79-77d9-8631-bffb-fb3417641e65</ID><Status>Succeeded</Status><HttpStatusCode>200</HttpStatusCode></Operation>", { 'cache-control': 'no-cache',
  'content-length': '232',
  'content-type': 'application/xml; charset=utf-8',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'x-ms-request-id': 'de17f0d2b2b683e5ba5391d6615c4688',
  date: 'Mon, 06 Apr 2015 17:39:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/operations/9eaf7d7977d98631bffbfb3417641e65')
  .reply(200, "<Operation xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><ID>9eaf7d79-77d9-8631-bffb-fb3417641e65</ID><Status>Succeeded</Status><HttpStatusCode>200</HttpStatusCode></Operation>", { 'cache-control': 'no-cache',
  'content-length': '232',
  'content-type': 'application/xml; charset=utf-8',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'x-ms-request-id': 'de17f0d2b2b683e5ba5391d6615c4688',
  date: 'Mon, 06 Apr 2015 17:39:03 GMT',
  connection: 'close' });
 return result; }]];