// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e59af84b-4f97-47b4-8ef0-ffab25a239e5',
    managementCertificate: {
      key: 'mockedKey',
      cert: 'mockedCert'
    },
    name: 'Windows Azure MSDN - Visual Studio Ultimate',
    registeredProviders: ['mobileservice'],
    registeredResourceNamespaces: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .post('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?targetMobileService=brettsam-east-test')
  .reply(200, "049e8532ab4d4e7fb2cefbc508b0e049", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '32',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '41ecdbcb94d48c879926d8a8b9067176',
  date: 'Mon, 06 Apr 2015 21:28:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .post('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?targetMobileService=brettsam-east-test')
  .reply(200, "049e8532ab4d4e7fb2cefbc508b0e049", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '32',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': '41ecdbcb94d48c879926d8a8b9067176',
  date: 'Mon, 06 Apr 2015 21:28:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=049e8532ab4d4e7fb2cefbc508b0e049')
  .reply(200, "Running", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '7',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'a1c98175d3f5848ba7f9a5cfa52b8cd0',
  date: 'Mon, 06 Apr 2015 21:28:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/services/mobileservices/mobileservices/brettsam-west-test/migrate?operationId=049e8532ab4d4e7fb2cefbc508b0e049')
  .reply(200, "Completed", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '9',
  'content-type': 'text/plain; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-powered-by': 'ASP.NET',
  'x-ms-request-id': 'd3b0f0c2d35e882c938938991ff091d5',
  date: 'Mon, 06 Apr 2015 21:30:11 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .delete('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/applications/brettsam-east-testmobileservice')
  .reply(202, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'x-ms-request-id': '3a914a5d687a8ca99e11109b7e533a5f',
  date: 'Mon, 06 Apr 2015 21:30:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .delete('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/applications/brettsam-east-testmobileservice')
  .reply(202, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'x-ms-request-id': '3a914a5d687a8ca99e11109b7e533a5f',
  date: 'Mon, 06 Apr 2015 21:30:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/operations/3a914a5d687a8ca99e11109b7e533a5f')
  .reply(200, "<Operation xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><ID>3a914a5d-687a-8ca9-9e11-109b7e533a5f</ID><Status>Succeeded</Status><HttpStatusCode>200</HttpStatusCode></Operation>", { 'cache-control': 'no-cache',
  'content-length': '232',
  'content-type': 'application/xml; charset=utf-8',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'x-ms-request-id': 'd2b2fb3d344885a089350187e2a55857',
  date: 'Mon, 06 Apr 2015 21:30:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/e59af84b-4f97-47b4-8ef0-ffab25a239e5/operations/3a914a5d687a8ca99e11109b7e533a5f')
  .reply(200, "<Operation xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><ID>3a914a5d-687a-8ca9-9e11-109b7e533a5f</ID><Status>Succeeded</Status><HttpStatusCode>200</HttpStatusCode></Operation>", { 'cache-control': 'no-cache',
  'content-length': '232',
  'content-type': 'application/xml; charset=utf-8',
  server: '1.0.6198.213 (rd_rdfe_stable.150402-1703) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth3',
  'x-ms-request-id': 'd2b2fb3d344885a089350187e2a55857',
  date: 'Mon, 06 Apr 2015 21:30:12 GMT',
  connection: 'close' });
 return result; }]];